### ISSUE TITLE
Return list of found Bluetooth devices via scan 

### ISSUE THREAD

**Issue by adonaygyb** [NIAGroup/2020_Arduino_Pi_IOT_Project#29]
Description: This issue will track the effort of creating a python back-end data structure with calls for issuing a generic and BLE Bluetooth scan and identify available devices. 

Pass Criteria: 

- Issue a Flask command and gather unique ID for each arduino device connected. 
- Store each device info in a data structure. Class, Dict, etc...

Reach Goals:

- Trigger command from "Connect"/"Scan" button from the front-end.
- Return device ID back to the front-end.

**Comment by NerdboyQ** [comment]
@adonaygyb the OpenCvPi ble device info:
* name : "Arduino_PID_0",
* addr : "00:35:FF:0D:41:9B"
