### ISSUE TITLE
Create UltraSonic Sensor Reading Functions

### ISSUE THREAD

**Issue by NerdboyQ** [NIAGroup/2020_Arduino_Pi_IOT_Project#4]
### General Idea/Purpose
* Learn about Analog I/O pins and how to read the input
* Learn about reading Sensor output and analyzing the data to the respective sensor (i.e. value equation to convert to distance)
* Create function to read sensor value and output the estimated distance

### Sensor function requirements:
* The function should exist outside the main loop so it is contained
* The function should be called, and return a double/floating point position _(centimeters should be the expected unit of measurement)_
* The function should include a valid measurement range _(i.e. when objects are too close or too far, the readings will be compromised, so these values should be ignored. Maybe this reports as 0 by default?)_
* This function will eventually need a secondary function that considers how long the measurement has been within a certain range for a specific time period _(i.e. If the balanced position of the ping pong ball is 12cm, +/- 1.5cm of error, for 3 seconds we trigger a "balanced state reached")_
* The function should have a expected measurement duration. _(i.e. measure for 5 seconds, or 10 seconds then return the last measure value)_
* Eventually this function will be triggered by a received bluetooth command byte

### Test/Pass Expectation:
* The function should be able to return reading values.
* The desired measurement time should match the value passed in value (in seconds) the function expected argument.
   > NOTE : this may need to change to milliseconds in the future.

### _Considerations:_
_1. The sensor has 4 pins_
    *_TRIG - Trigger pin should be connected to any digital I/O pin as an **OUTPUT** (Currently pin 4)_ 
    *_ECHO - Echo pin should be connected to any digital I/O pin as an **INPUT**; to be read (Currently pin 5)_ 
    *_VCC - Supply voltage pin should be connected to the arduino 5V pin_ 
    *_GND - Ground should be connected to the arduino ground pin_ 
_2. The trigger pin has to be set to **HIGH** then **LOW** to start the ultrasonic pulse emission._
   >_NOTE : This means it should start at **LOW** and end with **LOW**, never leave it at **HIGH**_   

_3. **DO NOT WRITE TO THE ECHO PIN**, this pin is strictly for reading by the arduino_
   >_NOTE: The echo pin returns a series of pulses (HIGHS & LOWS, i.e. 101000100001). To read the series of pulses we use the pulseIn function. i.e. pulseIn(5,HIGH)_

![Wiring Diagram](https://raw.githubusercontent.com/NIAGroup/2020_Arduino_Pi_IOT_Project/master/arduino_pid_controller/img/UltrasonicSensor_Wiring_Diagram.PNG?token=AEZYIMFNSQNR3B37TVUR6R27GOUBC)

**Comment by Injoh** [comment]
@NerdboyQ Not sure why they even use a bread board for this connections. Looks like they had a double connection for the GND and 5V pins.

**Comment by NerdboyQ** [comment]
@Injoh that's usually done if the wires aren't long enough, and to keep the connections clean & organized.
