### ISSUE TITLE
Create Pairing Script for BT Classic/Smart devices

### ISSUE THREAD

**Issue by NerdboyQ** [NIAGroup/2020_Arduino_Pi_IOT_Project#52]
### General Idea/Purpose
* Understand pairing process requirements
* Create pairing process script
* This will be used for the backend developers

### Bluetooth Pairing Scripts Requirements:
* The script method should accept two arguments: bluetooth address & pairing pin
* Pairing pin will be a default value
* Return a failure status or a pass status
* This is only for bluetooth classic/smart devices that require a pairing pin (ble devices do not require pairing)

### Test & Pass Expectation:
* Verify successful pairing - Be sure that pairing works consistently

### _Considerations:_
_1. This will be executed from the webapp UI._
_2. The status should change based on the results of this process._

**Comment by jmpichar** [comment]
Looks good.
