### ISSUE TITLE
BT Communication Error when sending null bytes (0x00)

### ISSUE THREAD

**Issue by NerdboyQ** [NIAGroup/2020_Arduino_Pi_IOT_Project#81]
#### Terms
_request - message from the pi to the arduino_   
_response - message from the arduino to the pi_   

### Scenario:
* When a request is sent with a null byte, 0x00, the Arduino is having an issue processing the message. 
* The response is never sent and causes a failure message on the pi 
* Any non-zero byte that's sent does not cause this issue
> NOTE : This may be an arduino limitation, not sure as of yet. References search terms : "Arduino Serial Communication"

### Current Workaround:
* Never send a zero byte.

**Comment by Injoh** [comment]
Per a discussion with @NerdboyQ. We are currently able to accurately send the bytes 00 and also receive the correct bytes in response. I will be closing this issue as not reproducible.
